#!/usr/bin/env node
// ============================================================
//  Deterministic compliance report + validator for controls.json.
//  Zero dependencies (Node built-ins only).
//
//  Modes:
//    node compliance/report.mjs           human-readable coverage + gaps
//    node compliance/report.mjs --md      render COVERAGE.md to stdout
//    node compliance/report.mjs --check   validate the catalogue + verify
//                                          COVERAGE.md is current; exit != 0 on any
//                                          structural error or staleness (CI gate)
//
//  "Deterministic" = the coverage %, the gap lists, and the SoA are COMPUTED from
//  controls.json every run, never hand-maintained — so they cannot silently drift.
// ============================================================
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(DIR, '..');
const CATALOGUE = path.join(DIR, 'controls.json');
const COVERAGE_MD = path.join(DIR, 'COVERAGE.md');

const cat = JSON.parse(fs.readFileSync(CATALOGUE, 'utf8'));
const STATUSES = ['implemented', 'partial', 'organizational', 'planned'];

// ---- validation ------------------------------------------------------------
function validate() {
  const errs = [];
  const ids = new Set();
  const fwKeys = new Set(Object.keys(cat.frameworks));
  const riskIds = new Set((cat.risks || []).map((r) => r.id));
  for (const c of cat.controls) {
    if (!c.id) { errs.push('control with no id'); continue; }
    if (ids.has(c.id)) errs.push(`duplicate control id: ${c.id}`);
    ids.add(c.id);
    if (!c.title) errs.push(`${c.id}: missing title`);
    if (!STATUSES.includes(c.status)) errs.push(`${c.id}: invalid status '${c.status}'`);
    if (!c.frameworks || !Object.keys(c.frameworks).length) errs.push(`${c.id}: no framework mapping`);
    for (const k of Object.keys(c.frameworks || {})) {
      if (!fwKeys.has(k)) errs.push(`${c.id}: references unknown framework '${k}'`);
      if (cat.frameworks[k] && cat.frameworks[k].applicable === false) errs.push(`${c.id}: maps to non-applicable framework '${k}'`);
    }
    for (const r of c.risks || []) if (!riskIds.has(r)) errs.push(`${c.id}: references unknown risk '${r}'`);
    // Evidence files must exist for controls that claim to be built.
    if (['implemented', 'partial'].includes(c.status)) {
      if (!(c.evidence || []).length) errs.push(`${c.id}: ${c.status} but no evidence`);
      for (const e of c.evidence || []) {
        if (!fs.existsSync(path.join(ROOT, e))) errs.push(`${c.id}: evidence path not found: ${e}`);
      }
    }
  }
  return errs;
}

// ---- computation -----------------------------------------------------------
function coverage() {
  // MITRE is technique-based (per-control `mitre` arrays), not control-status-based
  // like the other frameworks (per-control `frameworks` maps) — so it's reported
  // separately, not as a status row.
  const applicable = Object.entries(cat.frameworks)
    .filter(([k, f]) => f.applicable && k !== 'mitre').map(([k]) => k);
  const perFw = {};
  for (const k of applicable) perFw[k] = { implemented: 0, partial: 0, organizational: 0, planned: 0, controls: [] };
  const techniques = new Set();
  let mitreControls = 0;
  for (const c of cat.controls) {
    for (const k of Object.keys(c.frameworks || {})) {
      if (perFw[k]) { perFw[k][c.status]++; perFw[k].controls.push(c.id); }
    }
    if ((c.mitre || []).length) mitreControls++;
    for (const t of c.mitre || []) techniques.add(t);
  }
  const gaps = {
    planned: cat.controls.filter((c) => c.status === 'planned').map((c) => c.id),
    partial: cat.controls.filter((c) => c.status === 'partial').map((c) => c.id),
    organizational: cat.controls.filter((c) => c.status === 'organizational').map((c) => c.id),
  };
  return { applicable, perFw, techniques: [...techniques].sort(), mitreControls, gaps };
}

// ---- rendering -------------------------------------------------------------
function renderMd() {
  const { applicable, perFw, techniques, mitreControls, gaps } = coverage();
  const L = [];
  L.push('# Compliance coverage (generated — do not edit)');
  L.push('');
  L.push('> Generated by `node compliance/report.mjs --md` from `compliance/controls.json`.');
  L.push('> Regenerate after editing the catalogue; CI fails if this file is stale.');
  L.push('');
  L.push(`Controls: **${cat.controls.length}** · MITRE ATT&CK techniques mitigated: **${techniques.length}**`);
  L.push('');
  L.push('## Coverage by framework (applicable)');
  L.push('');
  L.push('| Framework | Implemented | Partial | Organizational | Planned |');
  L.push('|---|---|---|---|---|');
  for (const k of applicable) {
    const f = perFw[k];
    L.push(`| ${cat.frameworks[k].name} | ${f.implemented} | ${f.partial} | ${f.organizational} | ${f.planned} |`);
  }
  L.push('');
  L.push('## Not applicable');
  L.push('');
  for (const [k, f] of Object.entries(cat.frameworks)) {
    if (f.applicable === false) L.push(`- **${f.name}** — ${f.rationale}`);
  }
  L.push('');
  L.push('## Open items (gaps to close)');
  L.push('');
  L.push(`- **Planned (not built):** ${gaps.planned.join(', ') || 'none'}`);
  L.push(`- **Partial (residual gap):** ${gaps.partial.join(', ') || 'none'}`);
  L.push(`- **Organizational (owner action):** ${gaps.organizational.join(', ') || 'none'}`);
  L.push('');
  L.push(`## MITRE ATT&CK — ${techniques.length} techniques mitigated across ${mitreControls} controls`);
  L.push('');
  L.push(techniques.join(', '));
  L.push('');
  L.push('## Statement of Applicability (control → status → frameworks → evidence)');
  L.push('');
  L.push('| Control | Status | Frameworks | MITRE | Evidence |');
  L.push('|---|---|---|---|---|');
  for (const c of cat.controls) {
    const fw = Object.entries(c.frameworks).map(([k, v]) => `${k}:${v.join('/')}`).join('; ');
    const ev = (c.evidence || []).join(', ') || '—';
    L.push(`| **${c.id}** ${c.title} | ${c.status} | ${fw} | ${(c.mitre || []).join(', ') || '—'} | ${ev} |`);
  }
  L.push('');
  return L.join('\n');
}

function renderSummary() {
  const { applicable, perFw, techniques, gaps } = coverage();
  const out = [];
  out.push(`Controls: ${cat.controls.length} | MITRE techniques mitigated: ${techniques.length}`);
  out.push('Coverage by framework:');
  for (const k of applicable) {
    const f = perFw[k];
    out.push(`  ${k.padEnd(10)} impl=${f.implemented} partial=${f.partial} org=${f.organizational} planned=${f.planned}`);
  }
  out.push(`Gaps → planned: [${gaps.planned.join(', ')}]`);
  out.push(`      partial: [${gaps.partial.join(', ')}]`);
  out.push(`      organizational: [${gaps.organizational.join(', ')}]`);
  out.push('Not applicable: ' + Object.values(cat.frameworks).filter((f) => f.applicable === false).map((f) => f.name).join(', '));
  return out.join('\n');
}

// ---- main ------------------------------------------------------------------
const mode = process.argv[2];
if (mode === '--md') {
  process.stdout.write(renderMd() + '\n');
} else if (mode === '--check') {
  const errs = validate();
  if (errs.length) { console.error('CATALOGUE INVALID:\n - ' + errs.join('\n - ')); process.exit(1); }
  const current = fs.existsSync(COVERAGE_MD) ? fs.readFileSync(COVERAGE_MD, 'utf8') : '';
  if (current.trim() !== (renderMd()).trim()) {
    console.error('COVERAGE.md is stale. Regenerate: node compliance/report.mjs --md > compliance/COVERAGE.md');
    process.exit(1);
  }
  console.log(`compliance OK — ${cat.controls.length} controls, catalogue valid, COVERAGE.md current.`);
} else {
  console.log(renderSummary());
}
