/* ============================================================
   Runtime config + MSAL (Entra ID) auth + the typed API client.
   Extracted from app.jsx so the network/auth layer is a standalone,
   testable module with no React/rendering dependency.
   ============================================================ */

import { friendlyError } from './errors.js';

/* ---------- runtime config (generated by the container) ---------- */
const CFG = window.APP_CONFIG || { TENANT_ID:'', SPA_CLIENT_ID:'', API_CLIENT_ID:'', API_BASE:'' };
export const API_BASE = CFG.API_BASE || '';                 // '' => same origin (nginx proxies /api)
export const CONFIG_OK = !!(CFG.TENANT_ID && CFG.SPA_CLIENT_ID && CFG.API_CLIENT_ID);

/* ---------- MSAL auth ---------- */
let msalApp = null, msalReady = null;
function buildMsal() {
  if (!CONFIG_OK || !window.msal) return null;
  return new window.msal.PublicClientApplication({
    auth: {
      clientId: CFG.SPA_CLIENT_ID,
      authority: `https://login.microsoftonline.com/${CFG.TENANT_ID}`,
      redirectUri: window.location.origin,
      postLogoutRedirectUri: window.location.origin,
    },
    cache: { cacheLocation: 'sessionStorage', storeAuthStateInCookie: false },
  });
}
const loginRequest = { scopes: ['openid', 'profile', `api://${CFG.API_CLIENT_ID}/access_as_user`] };

export async function initAuth() {
  if (!msalApp) msalApp = buildMsal();
  if (!msalApp) throw new Error('Auth is not configured (missing TENANT_ID / SPA_CLIENT_ID / API_CLIENT_ID).');
  if (!msalReady) {
    msalReady = (async () => {
      await msalApp.initialize();
      await msalApp.handleRedirectPromise();
      if (!msalApp.getActiveAccount() && msalApp.getAllAccounts()[0]) {
        msalApp.setActiveAccount(msalApp.getAllAccounts()[0]);
      }
    })();
  }
  await msalReady;
  return msalApp;
}
export const currentAccount = () => (msalApp ? msalApp.getActiveAccount() : null);
export async function signIn() { await initAuth(); await msalApp.loginRedirect(loginRequest); }
export async function signOut() { await initAuth(); await msalApp.logoutRedirect(); }
// Local sign-out (no Microsoft redirect / single-sign-out) — clears the local
// token cache so the next request forces an interactive login. Used by the
// inactivity timeout.
export async function localSignOut() {
  try {
    await initAuth();
    if (typeof msalApp.clearCache === 'function') { await msalApp.clearCache(); }
    if (typeof msalApp.setActiveAccount === 'function') { msalApp.setActiveAccount(null); }
  } catch (_) {}
}
export const IDLE_LOGOUT_MS = 15 * 60 * 1000;   // sign the user out after 15 min of inactivity
export async function getToken() {
  await initAuth();
  const account = msalApp.getActiveAccount();
  if (!account) { await msalApp.loginRedirect(loginRequest); return null; }
  try {
    const r = await msalApp.acquireTokenSilent({ ...loginRequest, account });
    return r.accessToken;
  } catch (e) {
    if (e instanceof window.msal.InteractionRequiredAuthError) {
      const r = await msalApp.acquireTokenPopup(loginRequest);
      return r.accessToken;
    }
    throw e;
  }
}

/* ---------- API client ---------- */
async function request(method, path, body) {
  const token = await getToken();
  const res = await fetch(API_BASE + path, {
    method,
    headers: { Authorization: `Bearer ${token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) throw await apiError(res);
  return res.status === 204 ? null : res.json();
}
// Build an Error with a user-friendly message, keeping the machine code + detail
// on the object so callers can branch or deep-link if they want.
async function apiError(res) {
  let code = null, detail = null;
  try { const j = await res.json(); code = j.error || null; detail = j.detail || null; } catch (_) { /* non-JSON body */ }
  const err = new Error(friendlyError(code, detail) || String(res.status));
  err.code = code; err.detail = detail; err.status = res.status;
  return err;
}
async function uploadRequest(method, path, fields, file) {
  const token = await getToken();
  const fd = new FormData();
  Object.entries(fields || {}).forEach(([k, v]) => { if (v !== undefined && v !== null) fd.append(k, Array.isArray(v) ? v.join(',') : v); });
  if (file) fd.append('file', file);
  const res = await fetch(API_BASE + path, { method, headers: { Authorization: `Bearer ${token}` }, body: fd });
  if (!res.ok) throw await apiError(res);
  return res.status === 204 ? null : res.json();
}
export const api = {
  me:             ()                  => request('GET',  '/api/me'),
  policies:       ()                  => request('GET',  '/api/policies'),
  document:       (id)                => request('GET',  `/api/policies/${id}/document`),
  sign:           (policyId, fullName)=> request('POST', '/api/signatures', { policyId, fullName, acknowledged: true }),
  signatures:     ()                  => request('GET',  '/api/signatures'),
  employees:      ()                  => request('GET',  '/api/employees'),
  addEmployee:    (e)                 => request('POST', '/api/employees', e),
  bulkImportEmployees:(rows)          => request('POST', '/api/employees/bulk', { rows }),
  setEmployeeManager:(oid, mgr)       => request('PUT',  `/api/employees/${oid}/manager`, { functionalManagerOid: mgr }),
  createPolicy:   (p)                 => request('POST', '/api/policies', p),
  trainings:      ()                  => request('GET',  '/api/trainings'),
  trainingGroups: ()                  => request('GET',  '/api/trainings/groups'),
  groupReach:     (ids)               => request('GET',  '/api/groups/reach?ids=' + encodeURIComponent((ids||[]).join(','))),
  createTraining: (fields, file)      => uploadRequest('POST', '/api/trainings', fields, file),
  updateTraining: (id, fields, file)  => uploadRequest('PUT',  `/api/trainings/${id}`, fields, file),
  archiveTraining:(id)                => request('DELETE', `/api/trainings/${id}`),
  managerDashboard:()                 => request('GET',  '/api/manager/dashboard'),
  managerReminders:()                 => request('POST', '/api/manager/reminders/run'),
  updatePolicy:   (id, p)             => request('PUT',  `/api/policies/${id}`, p),
  archivePolicy:  (id)                => request('DELETE', `/api/policies/${id}`),
  getQuiz:        (id)                => request('GET',  `/api/policies/${id}/quiz`),
  saveQuiz:       (id, q)             => request('POST', `/api/policies/${id}/quiz`, q),
  archiveQuiz:    (id)                => request('POST', `/api/policies/${id}/quiz/archive`),
  restoreQuiz:    (id)                => request('POST', `/api/policies/${id}/quiz/restore`),
  deleteQuiz:     (id)                => request('DELETE', `/api/policies/${id}/quiz`),
  submitQuiz:     (id, answers)       => request('POST', `/api/policies/${id}/quiz/attempt`, { answers }),
  archivedPolicies:()                 => request('GET',  '/api/policies-archived'),
  restorePolicy:  (id)                => request('POST', `/api/policies/${id}/restore`),
  browseSharePoint:(drive,path)       => request('GET',  '/api/sharepoint/browse?drive=' + encodeURIComponent(drive || '') + '&path=' + encodeURIComponent(path || '')),
  groupMembers:   (id)                => request('GET',  `/api/groups/${id}/members`),
  addGroupMember: (id, oid)           => request('POST', `/api/groups/${id}/members`, { employeeOid: oid }),
  removeGroupMember:(id, oid)         => request('DELETE', `/api/groups/${id}/members/${oid}`),
  audit:          ()                  => request('GET',  '/api/audit'),
  listBackups:    ()                  => request('GET',  '/api/admin/backups'),
  createBackup:   ()                  => request('POST', '/api/admin/backups'),
  groups:         ()                  => request('GET',  '/api/groups'),
  createGroup:    (g)                 => request('POST', '/api/groups', g),
  platformGroups: ()                  => request('GET',  '/api/platform-groups'),
  directoryGroups:()                  => request('GET',  '/api/directory-groups'),
  createPlatformGroup:(g)             => request('POST', '/api/platform-groups', g),
  mapGroup:       (adGroupId, platformGroupId) => request('POST', '/api/group-mappings', { adGroupId, platformGroupId }),
  unmapGroup:     (adId, pgId)        => request('DELETE', `/api/group-mappings/${adId}/${pgId}`),
  sync:           ()                  => request('POST', '/api/sync'),
  dashboard:      ()                  => request('GET',  '/api/dashboard'),
  dashboardByDept:()                  => request('GET',  '/api/dashboard/by-department'),
  dashboardByGroup:()                 => request('GET',  '/api/dashboard/by-group'),
  groupDetail:    (id)                => request('GET',  `/api/dashboard/group/${id}`),
  complianceReport:(scope)            => request('GET',  '/api/reports/compliance' + (scope && scope.group ? ('?group=' + encodeURIComponent(scope.group)) : scope && scope.department ? ('?department=' + encodeURIComponent(scope.department)) : '')),
  runReminders:   ()                  => request('POST', '/api/reminders/run'),
  integrations:   ()                  => request('GET',  '/api/integrations'),
  saveIntegrations:(body)             => request('PUT',  '/api/integrations', body),
  rotateFeedKey:  ()                  => request('POST', '/api/integrations/feed-key'),
  testForward:    ()                  => request('POST', '/api/integrations/test'),
  syncStatus:     ()                  => request('GET',  '/api/sync/status'),
  policyVersions: (id)                => request('GET',  `/api/policies/${id}/versions`),
  formerEmployees:()                  => request('GET',  '/api/employees/former'),
  quizAnalytics:  (id)                => request('GET',  `/api/policies/${id}/quiz/analytics`),
  archiveGroup:   (id)                => request('POST', `/api/groups/${id}/archive`),
  restoreGroup:   (id)                => request('POST', `/api/groups/${id}/restore`),
  deleteGroup:    (id)                => request('DELETE', `/api/groups/${id}`),
  archivedGroups: ()                  => request('GET',  '/api/groups-archived'),
};
